const concept = (name, ...keywords) => ({ name, keywords });
const variant = (question, expectedConcepts) => ({ question, expectedConcepts });
const item = (id, beginner, intermediate, advanced) => ({
  id,
  variants: { Beginner: beginner, Intermediate: intermediate, Advanced: advanced },
});

/** Curated prompts and private evaluation cues, organized by practice category. */
export const PRACTICE_QUESTION_BANK = {
  DSA: [
    item('dsa-search',
      variant('How does binary search work, and what is its time complexity?', [concept('Sorted search space', 'sorted array', 'sorted data'), concept('Halving', 'halve', 'half'), concept('O(log n)', 'o(log n)', 'logarithmic')]),
      variant('What conditions make binary search correct, and how do you avoid off-by-one errors?', [concept('Monotonic order', 'sorted', 'monotonic'), concept('Bounds', 'low', 'high', 'left', 'right'), concept('Loop invariant', 'invariant', 'search interval')]),
      variant('How would you use binary search to find the first true value of a monotonic predicate?', [concept('Monotonic predicate', 'monotonic', 'false then true'), concept('Boundary search', 'first true', 'lower bound', 'boundary'), concept('O(log n)', 'o(log n)', 'logarithmic')]),
    ),
    item('dsa-traversal',
      variant('What is the difference between breadth-first search and depth-first search?', [concept('Queue for BFS', 'queue', 'breadth first'), concept('Stack or recursion for DFS', 'stack', 'recursion', 'depth first'), concept('Traversal order', 'level', 'depth', 'order')]),
      variant('How do BFS and DFS behave on a disconnected graph, and what are their time costs?', [concept('Visit every component', 'every component', 'each component', 'unvisited'), concept('Visited set', 'visited'), concept('O(V + E)', 'o(v + e)', 'vertices and edges')]),
      variant('When does BFS find a shortest path, and why does that change for weighted graphs?', [concept('Unweighted graph', 'unweighted'), concept('Level order shortest path', 'level', 'fewest edges', 'shortest path'), concept('Weighted alternative', 'dijkstra', 'weighted', 'priority queue')]),
    ),
    item('dsa-cycle',
      variant('How can you detect a cycle in a singly linked list?', [concept('Slow pointer', 'slow pointer', 'tortoise'), concept('Fast pointer', 'fast pointer', 'hare'), concept('Pointers meet', 'meet', 'same node', 'cycle')]),
      variant('Explain Floyd’s cycle detection and how you find the cycle entry after detecting one.', [concept('Different pointer speeds', 'slow', 'fast', 'two speeds'), concept('Meeting point', 'meet', 'collision'), concept('Reset pointer to head', 'reset', 'head'), concept('Advance together', 'same pace', 'one step')]),
      variant('What are the time and space costs of Floyd’s algorithm, including the no-cycle case?', [concept('O(n) time', 'o(n)', 'linear time'), concept('O(1) space', 'o(1)', 'constant space'), concept('Null termination', 'null', 'end of list', 'no cycle')]),
    ),
    item('dsa-hashmap',
      variant('When is a hash map useful in an algorithm?', [concept('Key lookup', 'lookup', 'key'), concept('Fast average access', 'average o(1)', 'constant time', 'fast'), concept('Store associations', 'map', 'key value', 'frequency')]),
      variant('What are the average and worst-case lookup costs of a hash map, and why do they differ?', [concept('Average O(1)', 'average o(1)', 'constant time'), concept('Worst case O(n)', 'o(n)', 'linear'), concept('Collisions', 'collision', 'bucket')]),
      variant('How do load factor and collision strategy affect hash map performance?', [concept('Load factor', 'load factor'), concept('Collision handling', 'collision', 'chaining', 'open addressing'), concept('Resize or rehash', 'resize', 'rehash', 'rebucket')]),
    ),
    item('dsa-two-pointer',
      variant('How does the two-pointer technique help find a pair in a sorted array?', [concept('Sorted input', 'sorted'), concept('Move left or right pointer', 'left', 'right', 'pointer'), concept('Discard candidates', 'increase', 'decrease', 'move')]),
      variant('What invariant do you use when solving a pair-sum problem with two pointers?', [concept('Sorted array', 'sorted'), concept('Compare current sum', 'sum', 'target'), concept('Move pointer by comparison', 'too small', 'too large', 'move')]),
      variant('When is a sliding window preferable to a general two-pointer scan?', [concept('Contiguous range', 'contiguous', 'subarray', 'window'), concept('Maintain window state', 'window state', 'expand', 'shrink'), concept('Monotonic or nonnegative condition', 'nonnegative', 'monotonic', 'constraint')]),
    ),
  ],
  DBMS: [
    item('dbms-normalization',
      variant('What is database normalization, and what problem does it prevent?', [concept('Organize related data', 'organize', 'structure', 'decompose'), concept('Reduce redundancy', 'redundancy', 'duplicate'), concept('Prevent anomalies', 'anomalies', 'update anomaly', 'insertion anomaly')]),
      variant('How does moving a table from 1NF toward 3NF reduce update anomalies?', [concept('Atomic values', 'atomic', '1nf'), concept('Functional dependency', 'functional dependency'), concept('Remove transitive dependency', 'transitive', '3nf')]),
      variant('When might you intentionally denormalize a schema, and what trade-off does it introduce?', [concept('Read performance', 'read performance', 'fewer joins'), concept('Duplicate data', 'duplicate', 'redundant'), concept('Consistency or update cost', 'consistency', 'update', 'write')]),
    ),
    item('dbms-index',
      variant('What does a database index do, and what is one cost of adding indexes?', [concept('Faster lookup', 'lookup', 'search', 'read'), concept('Extra storage', 'storage', 'space'), concept('Slower writes', 'write', 'insert', 'update')]),
      variant('How does a B-tree index help range queries, and what is a clustered index?', [concept('Balanced tree', 'b-tree', 'balanced tree'), concept('Ordered range scan', 'range', 'ordered', 'leaf'), concept('Clustered data order', 'clustered', 'row order', 'physical order')]),
      variant('How would you decide whether a composite index helps a query with filters on multiple columns?', [concept('Predicate columns', 'where', 'filter', 'predicate'), concept('Column order or leftmost prefix', 'leftmost', 'column order', 'prefix'), concept('Query plan or selectivity', 'explain', 'query plan', 'selectivity')]),
    ),
    item('dbms-where-having',
      variant('What is the difference between WHERE and HAVING in SQL?', [concept('WHERE filters rows', 'where', 'rows', 'before grouping'), concept('HAVING filters groups', 'having', 'groups', 'after grouping'), concept('Aggregate context', 'aggregate', 'group by')]),
      variant('Why can’t a WHERE clause normally filter on an aggregate such as COUNT(*)?', [concept('WHERE runs before grouping', 'before group', 'where'), concept('HAVING runs after grouping', 'having', 'after group'), concept('Aggregate result', 'count', 'aggregate')]),
      variant('How would you filter grouped query results by an aggregate while preserving row-level filters?', [concept('Row predicates in WHERE', 'where', 'row'), concept('GROUP BY', 'group by', 'group'), concept('Aggregate predicate in HAVING', 'having', 'aggregate')]),
    ),
    item('dbms-acid',
      variant('What do the four ACID properties mean for a database transaction?', [concept('Atomicity', 'atomicity', 'all or nothing'), concept('Consistency and isolation', 'consistency', 'isolation'), concept('Durability', 'durability', 'persist')]),
      variant('How do isolation and durability address different transaction risks?', [concept('Isolation between transactions', 'isolation', 'concurrent'), concept('Durability after commit', 'durability', 'commit', 'persist'), concept('Crash or concurrency distinction', 'crash', 'concurrent', 'interference')]),
      variant('What anomaly can occur under weak isolation, and what trade-off comes with stronger isolation?', [concept('Dirty, nonrepeatable, or phantom read', 'dirty read', 'nonrepeatable', 'phantom'), concept('Isolation level', 'isolation level', 'serializable'), concept('Concurrency cost', 'concurrency', 'throughput', 'locking')]),
    ),
    item('dbms-keys',
      variant('What is the difference between a primary key and a unique constraint?', [concept('Uniqueness', 'unique', 'duplicate'), concept('Primary key identifies a row', 'identify', 'row', 'primary'), concept('Nullability distinction', 'null', 'not null')]),
      variant('How do primary keys, candidate keys, and foreign keys relate?', [concept('Candidate key uniquely identifies', 'candidate', 'unique'), concept('Primary key chosen candidate', 'primary', 'chosen'), concept('Foreign key references another key', 'foreign', 'references')]),
      variant('How would you model a many-to-many relationship while preserving referential integrity?', [concept('Junction table', 'junction', 'bridge', 'join table'), concept('Two foreign keys', 'foreign key', 'references'), concept('Composite uniqueness', 'composite', 'unique', 'primary key')]),
    ),
  ],
  OS: [
    item('os-process-thread',
      variant('What is one key difference between a process and a thread?', [concept('Separate process address spaces', 'address space', 'isolated memory'), concept('Threads share process memory', 'share memory', 'shared address space'), concept('Thread execution state', 'stack', 'register', 'program counter')]),
      variant('Which resources do threads share within a process, and which remain thread-local?', [concept('Heap or code shared', 'heap', 'code', 'shared'), concept('Stack local', 'stack', 'private'), concept('Registers or program counter local', 'register', 'program counter')]),
      variant('What synchronization risks appear when threads share mutable state, and how can they be managed?', [concept('Race condition', 'race condition', 'concurrent access'), concept('Mutual exclusion or lock', 'mutex', 'lock', 'critical section'), concept('Deadlock or ordering concern', 'deadlock', 'lock order', 'ordering')]),
    ),
    item('os-deadlock',
      variant('What is a deadlock in an operating system?', [concept('Processes wait indefinitely', 'wait', 'blocked', 'indefinitely'), concept('Resources held', 'resource', 'lock'), concept('Circular dependency', 'circular', 'cycle', 'waiting')]),
      variant('Name the four Coffman conditions required for deadlock.', [concept('Mutual exclusion', 'mutual exclusion'), concept('Hold and wait', 'hold and wait'), concept('No preemption and circular wait', 'no preemption', 'circular wait')]),
      variant('How can a system prevent deadlock by imposing a resource ordering?', [concept('Global order', 'order', 'ordering', 'hierarchy'), concept('Avoid circular wait', 'circular wait', 'cycle'), concept('Consistent acquisition', 'acquire', 'lock order', 'same order')]),
    ),
    item('os-memory',
      variant('What is virtual memory, and why is it useful?', [concept('Address space abstraction', 'address space', 'virtual address'), concept('Mapping to physical memory', 'physical memory', 'mapping', 'page table'), concept('Isolation or larger logical space', 'isolation', 'larger', 'process')]),
      variant('What happens during a page fault, and when does it require disk I/O?', [concept('Page not resident', 'not in memory', 'absent', 'missing page'), concept('Operating system handles fault', 'operating system', 'os', 'handler'), concept('Load page from backing store', 'disk', 'backing store', 'load page')]),
      variant('How do page size and TLB hit rate affect address translation performance?', [concept('Page table translation', 'page table', 'translation'), concept('TLB caches mappings', 'tlb', 'cache'), concept('Trade-off of page size', 'page size', 'fragmentation', 'working set')]),
    ),
    item('os-context',
      variant('What is a context switch?', [concept('Save current state', 'save', 'register', 'state'), concept('Restore another task', 'restore', 'switch', 'another process'), concept('Scheduling overhead', 'overhead', 'scheduler')]),
      variant('What state must be preserved when switching a CPU from one process to another?', [concept('Registers and program counter', 'register', 'program counter'), concept('Stack or memory context', 'stack', 'address space'), concept('Process control block', 'pcb', 'process control block')]),
      variant('Why can too-frequent context switching reduce throughput?', [concept('Save and restore overhead', 'overhead', 'save', 'restore'), concept('Cache disruption', 'cache', 'locality'), concept('Less useful execution time', 'useful work', 'throughput', 'cpu time')]),
    ),
    item('os-scheduling',
      variant('What is the purpose of CPU scheduling?', [concept('Choose runnable task', 'choose', 'select', 'runnable'), concept('Share CPU time', 'cpu time', 'processor'), concept('Fairness or responsiveness', 'fair', 'response', 'throughput')]),
      variant('How do round-robin and shortest-job-first scheduling differ?', [concept('Time quantum', 'quantum', 'time slice'), concept('Shortest burst first', 'shortest job', 'burst'), concept('Fairness versus waiting time', 'fair', 'waiting', 'response')]),
      variant('How can priority scheduling cause starvation, and how can aging help?', [concept('Low-priority starvation', 'starvation', 'wait indefinitely'), concept('Aging raises priority', 'aging', 'increase priority'), concept('Trade-off with responsiveness', 'response', 'fairness', 'priority')]),
    ),
  ],
  Networking: [
    item('net-tcp-udp',
      variant('What is one difference between TCP and UDP?', [concept('TCP connection or reliability', 'connection', 'reliable', 'ordered'), concept('UDP connectionless', 'connectionless', 'datagram'), concept('Use case trade-off', 'latency', 'overhead', 'trade')]),
      variant('How do TCP retransmission and ordering compare with UDP delivery?', [concept('Acknowledgment or retransmission', 'ack', 'retransmit', 'retransmission'), concept('Ordered byte stream', 'ordered', 'sequence number', 'byte stream'), concept('UDP lacks delivery guarantee', 'no guarantee', 'unreliable', 'udp')]),
      variant('When would you choose UDP over TCP for a real-time application?', [concept('Latency-sensitive', 'latency', 'real time'), concept('Tolerate loss or app-level recovery', 'packet loss', 'tolerate loss', 'application layer'), concept('Avoid connection overhead', 'overhead', 'connectionless')]),
    ),
    item('net-url',
      variant('What are the main steps after you enter a URL in a browser?', [concept('DNS lookup', 'dns', 'resolve'), concept('Connect to server', 'tcp', 'connect', 'handshake'), concept('HTTP request and response', 'http', 'request', 'response')]),
      variant('Trace a browser request from DNS resolution through TLS and the HTTP response.', [concept('DNS resolution', 'dns', 'resolve'), concept('TCP and TLS handshake', 'tcp', 'tls', 'handshake'), concept('HTTP request/response', 'http', 'request', 'response')]),
      variant('How can caching, connection reuse, and TLS affect the steps and latency of a browser request?', [concept('Cache can avoid lookup or request', 'cache', 'cached'), concept('Connection reuse', 'keep-alive', 'reuse', 'persistent connection'), concept('TLS setup or session reuse', 'tls', 'session reuse', 'handshake')]),
    ),
    item('net-http-status',
      variant('What do HTTP status code groups 2xx, 4xx, and 5xx represent?', [concept('2xx success', 'success', '2xx'), concept('4xx client error', 'client error', '4xx'), concept('5xx server error', 'server error', '5xx')]),
      variant('When would an API return 401, 403, and 404?', [concept('401 unauthenticated', '401', 'unauthenticated'), concept('403 forbidden', '403', 'forbidden', 'not allowed'), concept('404 not found', '404', 'not found')]),
      variant('How should an API choose between 400, 409, and 422 for a rejected request?', [concept('400 malformed request', '400', 'malformed'), concept('409 state conflict', '409', 'conflict'), concept('422 semantic validation', '422', 'validation', 'unprocessable')]),
    ),
    item('net-dns',
      variant('What does DNS do when a client visits a domain name?', [concept('Resolve domain name', 'resolve', 'domain'), concept('Return an address', 'ip address', 'address', 'record'), concept('Caching', 'cache', 'ttl')]),
      variant('How do recursive and authoritative DNS servers participate in name resolution?', [concept('Recursive resolver', 'recursive', 'resolver'), concept('Authoritative server', 'authoritative'), concept('Record lookup or caching', 'record', 'cache', 'ttl')]),
      variant('What does a DNS TTL control, and what trade-off does a shorter TTL create?', [concept('Cache lifetime', 'cache', 'lifetime', 'ttl'), concept('Freshness or propagation', 'fresh', 'propagation', 'update'), concept('More queries or load', 'queries', 'load', 'traffic')]),
    ),
    item('net-rest',
      variant('What does it mean for an API to follow REST principles?', [concept('Resources identified by URLs', 'resource', 'url'), concept('HTTP methods', 'http method', 'get', 'post', 'put', 'delete'), concept('Stateless requests', 'stateless')]),
      variant('How do HTTP methods and status codes express resource operations in a REST API?', [concept('Resource representation', 'resource', 'representation'), concept('Method semantics', 'get', 'post', 'put', 'delete'), concept('Status code meaning', 'status code', '201', '204', '404')]),
      variant('How would you design idempotent updates and error responses for a REST endpoint?', [concept('Idempotent operation', 'idempotent', 'same result'), concept('Method choice', 'put', 'patch', 'delete'), concept('Consistent status and error body', 'status', 'error response', 'error body')]),
    ),
  ],
  OOP: [
    item('oop-encapsulation',
      variant('What is the difference between encapsulation and abstraction?', [concept('Encapsulation hides state', 'hide state', 'private', 'encapsulation'), concept('Abstraction exposes essential behavior', 'essential behavior', 'interface', 'abstraction'), concept('Separate concerns', 'separate', 'implementation')]),
      variant('How can an interface provide abstraction while a class uses encapsulation?', [concept('Interface contract', 'interface', 'contract'), concept('Hidden implementation or state', 'private', 'hidden', 'implementation'), concept('Public behavior', 'public method', 'behavior')]),
      variant('When can excessive encapsulation or abstraction make a design harder to use?', [concept('Unnecessary indirection', 'indirection', 'over abstraction', 'unnecessary'), concept('Leaky or awkward API', 'api', 'leak', 'awkward'), concept('Balance with concrete needs', 'trade-off', 'tradeoff', 'balance')]),
    ),
    item('oop-composition',
      variant('What is one difference between inheritance and composition?', [concept('Inheritance is-a relationship', 'is-a', 'inherit'), concept('Composition has-a relationship', 'has-a', 'compose'), concept('Reuse behavior', 'reuse', 'behavior')]),
      variant('Why might composition be preferred over inheritance for sharing behavior?', [concept('Loose coupling', 'loose coupling', 'decouple'), concept('Delegate to collaborators', 'delegate', 'collaborator'), concept('Avoid rigid hierarchy', 'hierarchy', 'rigid')]),
      variant('How would you decide between inheritance and composition for two related domain objects?', [concept('Subtype substitutability', 'subtype', 'substitutability', 'liskov'), concept('Has-a versus is-a', 'has-a', 'is-a'), concept('Change or coupling trade-off', 'coupling', 'change', 'trade-off')]),
    ),
    item('oop-polymorphism',
      variant('What is polymorphism in object-oriented programming?', [concept('Shared interface or base type', 'interface', 'base type'), concept('Different implementations', 'different implementation', 'override'), concept('Dynamic behavior', 'runtime', 'dynamic dispatch')]),
      variant('How does runtime polymorphism allow a caller to work with different implementations?', [concept('Common contract', 'contract', 'interface', 'base class'), concept('Override method', 'override'), concept('Dispatch at runtime', 'runtime', 'dispatch')]),
      variant('What design trade-offs arise when a system relies heavily on subtype polymorphism?', [concept('Extensibility', 'extend', 'new implementation'), concept('Indirection or complexity', 'indirection', 'complexity'), concept('Substitutability', 'substitute', 'liskov')]),
    ),
    item('oop-interface-abstract',
      variant('What is a basic difference between an interface and an abstract class?', [concept('Interface contract', 'contract', 'interface'), concept('Abstract class can share implementation', 'shared implementation', 'abstract class'), concept('Inheritance constraint', 'inherit', 'multiple')]),
      variant('When would you use an abstract class instead of an interface?', [concept('Shared state or behavior', 'shared behavior', 'state'), concept('Common base relationship', 'base class', 'common'), concept('Contract only suits interface', 'contract', 'interface')]),
      variant('How do language features affect the interface-versus-abstract-class decision?', [concept('Language-specific capabilities', 'language', 'default method'), concept('Multiple interfaces or inheritance', 'multiple inheritance', 'multiple interface'), concept('Shared implementation needs', 'implementation', 'shared state')]),
    ),
    item('oop-solid',
      variant('What does the single responsibility principle suggest about a class?', [concept('One reason to change', 'one reason', 'single responsibility'), concept('Focused responsibility', 'focused', 'responsibility'), concept('Cohesion', 'cohesion')]),
      variant('How does dependency inversion reduce coupling between high- and low-level modules?', [concept('Depend on abstractions', 'abstraction', 'interface'), concept('High and low level', 'high level', 'low level'), concept('Inject implementation', 'inject', 'dependency injection')]),
      variant('How would you refactor a class that handles persistence, validation, and HTTP responses?', [concept('Separate responsibilities', 'separate', 'responsibility', 'class'), concept('Use abstractions or collaborators', 'interface', 'abstraction', 'collaborator'), concept('Keep changes isolated', 'isolated', 'coupling', 'test')]),
    ),
  ],
  JavaScript: [
    item('js-bindings',
      variant('How do var, let, and const differ in JavaScript?', [concept('Scope', 'scope', 'block scoped', 'function scoped'), concept('Reassignment', 'reassign', 'assignment'), concept('Hoisting or temporal dead zone', 'hoist', 'temporal dead zone')]),
      variant('What happens when let or const is accessed before its declaration?', [concept('Temporal dead zone', 'temporal dead zone', 'tdz'), concept('Block scope', 'block scope', 'block-scoped'), concept('Reference error', 'referenceerror', 'reference error')]),
      variant('How can var hoisting and block-scoped declarations cause bugs in loops or conditionals?', [concept('Function-scoped var', 'function scope', 'var'), concept('Block scope for let/const', 'block scope', 'let', 'const'), concept('Closure or captured binding', 'closure', 'captured', 'loop')]),
    ),
    item('js-closure',
      variant('What is a closure in JavaScript?', [concept('Function', 'function'), concept('Lexical environment', 'lexical', 'scope'), concept('Retains access after outer function returns', 'outer', 'returns', 'retain', 'access')]),
      variant('How can a closure preserve private state between function calls?', [concept('Enclosing scope', 'enclosing', 'lexical scope'), concept('Captured variable', 'capture', 'variable'), concept('Persistent state', 'private', 'state', 'retain')]),
      variant('What closure-related issue can arise when creating callbacks inside a loop, and how can it be avoided?', [concept('Shared or captured binding', 'shared', 'captured', 'binding'), concept('Block-scoped declaration', 'let', 'block scope'), concept('Create per-iteration scope', 'per iteration', 'scope', 'factory')]),
    ),
    item('js-promises',
      variant('What is a Promise, and what states can it be in?', [concept('Asynchronous result', 'asynchronous', 'async', 'future value'), concept('Pending', 'pending'), concept('Fulfilled or rejected', 'fulfilled', 'resolved', 'rejected')]),
      variant('How does async/await handle a rejected Promise?', [concept('Await Promise', 'await'), concept('Rejection throws', 'throw', 'reject', 'rejection'), concept('Try/catch', 'try', 'catch')]),
      variant('How do Promise.all and Promise.allSettled differ when one operation fails?', [concept('Promise.all rejects early', 'reject', 'promise.all'), concept('allSettled waits for every result', 'allsettled', 'every result'), concept('Choose by failure handling needs', 'failure', 'trade-off', 'tradeoff')]),
    ),
    item('js-event-loop',
      variant('What role does the JavaScript event loop play?', [concept('Call stack', 'call stack'), concept('Queue', 'queue', 'task'), concept('Schedule callbacks after stack clears', 'stack clears', 'callback', 'event loop')]),
      variant('How do microtasks and timer callbacks differ in event-loop ordering?', [concept('Promise callbacks are microtasks', 'promise', 'microtask'), concept('Timers are task or macrotask queue', 'timer', 'task queue', 'macrotask'), concept('Microtasks run before next task', 'before next task', 'drain', 'priority')]),
      variant('Why can recursively scheduling microtasks delay rendering or timers?', [concept('Microtask queue drains', 'drain', 'microtask queue'), concept('Starvation of later tasks', 'starve', 'delay', 'timer'), concept('Yield to event loop', 'yield', 'task', 'render')]),
    ),
    item('js-this',
      variant('How is the value of this generally determined for a JavaScript function call?', [concept('Call site', 'call site', 'invocation'), concept('Method receiver', 'receiver', 'object'), concept('Arrow function lexical this', 'arrow', 'lexical')]),
      variant('How do arrow functions differ from regular functions in their handling of this?', [concept('Lexically captured this', 'lexical', 'capture'), concept('Regular function call binding', 'call site', 'dynamic'), concept('No own this', 'own this', 'no own')]),
      variant('How can extracting a method from an object change its this value, and how do bind or closures help?', [concept('Receiver lost', 'receiver', 'undefined', 'lost'), concept('bind fixes context', 'bind'), concept('Closure or wrapper', 'closure', 'wrapper', 'arrow')]),
    ),
  ],
  Interview: [
    item('interview-intro',
      variant('Tell me about a project you are proud of.', [concept('Context or goal', 'goal', 'problem', 'context'), concept('Personal contribution', 'i built', 'i worked', 'contribution'), concept('Outcome or learning', 'result', 'outcome', 'learned')]),
      variant('Describe a project decision you made and how you measured its result.', [concept('Decision and alternatives', 'decision', 'alternative', 'chose'), concept('Evidence or measurement', 'measure', 'metric', 'evidence'), concept('Outcome or lesson', 'result', 'outcome', 'learned')]),
      variant('Explain a project trade-off you would revisit if you had another week.', [concept('Specific trade-off', 'trade-off', 'tradeoff', 'trade'), concept('Reasoning or constraint', 'because', 'constraint', 'reason'), concept('Revisit plan or impact', 'revisit', 'change', 'impact')]),
    ),
    item('interview-conflict',
      variant('Tell me about a time you worked through a disagreement with a teammate.', [concept('Disagreement context', 'disagree', 'conflict', 'difference'), concept('Listening or collaboration', 'listen', 'discuss', 'collaborate'), concept('Resolution or result', 'resolve', 'result', 'outcome')]),
      variant('How did you handle a disagreement when the team had a deadline?', [concept('Understand viewpoints', 'listen', 'viewpoint', 'understand'), concept('Compare evidence or options', 'evidence', 'option', 'trade-off'), concept('Decision and outcome', 'decide', 'result', 'outcome')]),
      variant('Describe a disagreement where you changed your position after reviewing new information.', [concept('Initial position', 'initial', 'i thought', 'my view'), concept('New evidence and reflection', 'evidence', 'information', 'review'), concept('Changed decision or lesson', 'changed', 'revised', 'learned')]),
    ),
    item('interview-challenge',
      variant('Describe a challenging problem you solved.', [concept('Challenge', 'challenge', 'problem'), concept('Actions taken', 'i tried', 'i built', 'action'), concept('Result', 'result', 'outcome', 'solved')]),
      variant('How did you break down a complex problem when the first approach failed?', [concept('Break into parts', 'break down', 'decompose', 'smaller'), concept('Evaluate approach', 'failed', 'debug', 'evaluate'), concept('Iterate and validate', 'iterate', 'test', 'validate')]),
      variant('What evidence would convince you that your solution to a difficult problem is robust?', [concept('Edge cases', 'edge case', 'boundary'), concept('Testing or proof', 'test', 'proof', 'invariant'), concept('Complexity or trade-offs', 'complexity', 'trade-off', 'performance')]),
    ),
    item('interview-feedback',
      variant('What is a piece of feedback that changed how you work?', [concept('Specific feedback', 'feedback', 'told me', 'suggested'), concept('Response or action', 'changed', 'started', 'action'), concept('Result', 'result', 'improved', 'learned')]),
      variant('How did you apply feedback that was difficult to hear?', [concept('Understand feedback', 'understand', 'clarify', 'feedback'), concept('Concrete adjustment', 'changed', 'adjusted', 'practice'), concept('Follow-up result', 'result', 'improved', 'follow up')]),
      variant('How do you distinguish useful feedback from a preference that may not fit the situation?', [concept('Ask for context', 'context', 'clarify'), concept('Evidence or goal', 'evidence', 'goal', 'user'), concept('Adapt and communicate', 'adapt', 'communicate', 'explain')]),
    ),
    item('interview-priority',
      variant('How do you prioritize when several tasks are due at once?', [concept('Deadlines or impact', 'deadline', 'impact', 'urgent'), concept('Break down tasks', 'break down', 'estimate', 'tasks'), concept('Communicate plan', 'communicate', 'plan', 'update')]),
      variant('How would you handle competing tasks when a dependency might block the team?', [concept('Identify dependency', 'dependency', 'blocked'), concept('Prioritize impact and urgency', 'impact', 'urgent', 'priority'), concept('Communicate or renegotiate', 'communicate', 'renegotiate', 'update')]),
      variant('How do you revise your priorities when an important assumption turns out to be wrong?', [concept('Validate assumption', 'assumption', 'validate'), concept('Reassess impact', 'impact', 'risk', 'priority'), concept('Communicate and adapt', 'communicate', 'adapt', 'plan')]),
    ),
  ],
};

export const PRACTICE_CATEGORIES = Object.keys(PRACTICE_QUESTION_BANK);

export const selectPracticeQuestions = ({ category, difficulty, count, rotation = 0 }) => {
  const bank = PRACTICE_QUESTION_BANK[category];
  if (!bank) return [];
  return Array.from({ length: count }, (_, offset) => {
    const selected = bank[(rotation + offset) % bank.length];
    const variantData = selected.variants[difficulty];
    return {
      questionId: selected.id,
      question: variantData.question,
      expectedConcepts: variantData.expectedConcepts,
    };
  });
};
